// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqolgcitkmvuoonoinbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlxb2xnY2l0a212dW9vbm9pbmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzE5MzQsImV4cCI6MjA2MTQwNzkzNH0.reNWJvw1cNG5fXMPP9bs3tYVTtB_ZeAE95AUIynDvLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);